
FRAMERATE = 64
TICKRATE = 8

UPARROW = '1'
LEFTARROW = '2'
RIGHTARROW = '3'
DOWNARROW = '4'
SHOOT_BUTTON = '5'
ACTION_NUMBER = 'a'

CAR_SIZE = 16

POWERUP_HEALTH_AMT = 10

POWERUP_HEALTH = 0
POWERUP_JUICE = 1
POWERUP_AMMO = 2
POWERUP_BONUS = 3

ACTIONS = {UPARROW: False, LEFTARROW: False, RIGHTARROW: False, DOWNARROW: False, SHOOT_BUTTON: False}
