
FRAMERATE = 60

UPARROW = '1'
LEFTARROW = '2'
RIGHTARROW = '3'
DOWNARROW = '4'

POWERUP_HEALTH_AMT = 10

POWERUP_HEALTH = 0
POWERUP_JUICE = 1
POWERUP_AMMO = 2
POWERUP_BONUS = 3

ACTIONS = {UPARROW: False, LEFTARROW: False, RIGHTARROW: False, DOWNARROW: False}
